(setq *default-page-bounds* #(0 0 420 518))

(defun do-page (filename)
  (let* ((data (json:decode-json-from-source (make-pathname :name filename :type "json")))
         (page (cdr (assoc :page data)))
         (width (- (cdr (assoc :width page)) 30))   ;in mm
         (height (cdr (assoc :height page))) ;in mm
         (number-of-rows (cdr (assoc :rows page)))
         (number-of-cols (cdr (assoc :cols page)))
         (row-height (float (/ height number-of-rows)))
         (col-width (float (/ width number-of-cols)))
         (swatches (cdr (assoc :swatches data)))
         (helvetica (pdf:get-font "Helvetica")))
    (pdf:with-document ()
      (pdf:with-page ()
        (dotimes (row number-of-rows)
          (let ((swatch-row (nth row swatches)))
            (do* ((col 0 (1+ col))
                  (swatch (first swatch-row)
                          (nth col swatch-row)))
                 ((>= col number-of-cols))
              (setq col (+ col (do-swatch swatch row col row-height col-width)))))))
      (pdf:write-document (make-pathname :name filename :type "pdf")))))

(defun string-width (string font font-size)
  (reduce #'+ (map 'list (lambda (x) (pdf:get-char-width x font font-size)) string)))

(defun prefix-length (string index font font-size)
  (string-width (subseq string 0 index) font font-size))


(defun split-text (string font font-size max-width)
  (cond ((equal (length string) 0)
         '("" ""))
        ((< (string-width string font font-size) max-width)
         (list string ""))
        (t (do ((split-point (1- (length string)) (1- split-point)))
               ((or (equal split-point 0)
                    (and (< (prefix-length string split-point font font-size) max-width)
                         (equal (char string split-point) #\Space)))
                (if (equal split-point 0)
                    (list string "")
                    (list (subseq string 0 split-point)
                          (subseq string (1+ split-point)))))))))


(defun do-swatch (swatch row col row-height col-width)
  (let* ((x (* col col-width))
         (y (* row row-height))
         (top (1- (+ y row-height)))
         (helvetica (pdf:get-font "Helvetica"))
         (brand (if swatch (cdr (assoc :brand swatch)) ""))
         (name (if swatch (cdr (assoc :name swatch)) ""))
         (full-pan (and swatch
                        (or (cdr (assoc :full swatch))
                            nil)))
         (name-lines (split-text name helvetica 5.0 (- (* col-width (if full-pan 2 1)) 5)))
         (line1 (first name-lines))
         (line2 (second name-lines)))
    (pdf:rotate 0)
    (pdf:set-rgb-stroke 0.0 0.0 0.0)
    (pdf:set-rgb-fill 1.0 1.0 1.0)
    (pdf:rectangle x y (* col-width (if full-pan 2 1)) row-height)
    (pdf:close-fill-and-stroke)
    (pdf:in-text-mode
      (pdf:set-font helvetica 5.0)
      (pdf:set-rgb-stroke 0.0 0.0 0.0)
      (pdf:set-rgb-fill 0.0 0.0 0.0)
      (pdf:move-to (+ x 2) (- top 5))
      (pdf:draw-text (format nil "~A" brand))
      (pdf:move-to (+ x 2) (+ y 7))
      (pdf:draw-text (format nil "~A" line1))
      (pdf:move-to (+ x 2) (+ y 2))
      (pdf:draw-text (format nil "~A" line2)))
    (if full-pan 1 0)))
