
(defun do-page (filename)
  (let* ((data (json:decode-json-from-source (make-pathname :name filename :type "json")))
         (page (cdr (assoc :page data)))
         (title (cdr (assoc :title page)))
         (width (- (cdr (assoc :width page)) 30))   ;in mm
         (height (cdr (assoc :height page))) ;in mm
         (number-of-rows (cdr (assoc :rows page)))
         (number-of-cols (cdr (assoc :cols page)))
         (row-height (float (/ height number-of-rows)))
         (col-width (float (/ width number-of-cols)))
         (swatches (cdr (assoc :swatches data)))
         (helvetica (pdf:get-font "Helvetica")))
    (pdf:with-document ()
      (pdf:with-page ()
        (dotimes (col number-of-cols)
          (dotimes (row number-of-rows)
            (do-swatch (nth (+ (* col number-of-rows) row) swatches) row col row-height col-width)))
        (pdf:in-text-mode
          (pdf:set-font (pdf:get-font "Helvetica") 18)
          (pdf:set-rgb-stroke 0.0 0.0 0.0)
          (pdf:set-rgb-fill 0.0 0.0 0.0)
          (pdf:rotate 270)
          (pdf:move-to (* -1 (- height 10)) 10)
          (pdf:draw-text title)))
      (pdf:write-document (make-pathname :name filename :type "pdf")))))


(defun do-swatch (swatch row col row-height col-width)
  (let* ((x (+ 30 (* col col-width)))
         (y (* row row-height))
         (top (1- (+ y row-height)))
         (helvetica (pdf:get-font "Helvetica")))
    (pdf:rotate 0)
    (pdf:set-rgb-stroke 0.0 0.0 0.0)
    (pdf:set-rgb-fill 1.0 1.0 1.0)
    (pdf:rectangle x y col-width row-height)
    (pdf:close-fill-and-stroke)
    (unless (null swatch)
      (let ((number (cdr (assoc :number swatch)))
            (name (cdr (assoc :name swatch)))
            (lightfastness (cdr (assoc :lightfastness swatch)))
            (pigments (cdr (assoc :pigments swatch))))
        (pdf:in-text-mode
          (pdf:set-font helvetica 8.0)
          (pdf:set-rgb-stroke 0.0 0.0 0.0)
          (pdf:set-rgb-fill 0.0 0.0 0.0)
          (pdf:move-to (+ x 5) (- top 10))
          (pdf:draw-text (format nil "~A" name))
          (pdf:move-to (+ x 5) (- top 20))
          (pdf:draw-text (format nil "~A" number))
          (pdf:move-to (+ x 5) (- top 30))
          (pdf:draw-text (format nil "~A" (nth lightfastness '("    " "*   " "**  " "*** " "****"))))
          (pdf:move-to (+ x 5) (+ y 5))
          (pdf:draw-text (format nil "~A" pigments))
          )))))
